name: Build and Deploy (QA & PROD)
# This workflow runs Supabase migrations for QA and PROD environments.

on:
  push:
    branches:
      - master
      - main
      - release

jobs:
  build-and-deploy-qa:
    name: Build and Deploy to QA
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Pulls your repo code
      - name: Install Supabase CLI
        run: |
          wget -O /tmp/supabase.tar.gz https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
          cd /tmp
          tar -xzf supabase.tar.gz
          sudo cp supabase /usr/local/bin/
          sudo chmod +x /usr/local/bin/supabase
          supabase --version
        # Installs Supabase CLI globally
      - name: Run Supabase migrations (QA)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.QA_SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.QA_SUPABASE_DB_PASSWORD }}
        run: |
          supabase link --project-ref ${{ secrets.QA_SUPABASE_PROJECT_REF }}
          supabase db push --password $SUPABASE_DB_PASSWORD
        # Links to QA Supabase project and applies migrations
      - name: Deploy Edge Functions (QA)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.QA_SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy --project-ref ${{ secrets.QA_SUPABASE_PROJECT_REF }}
        # Deploys all edge functions to QA environment

  build-and-deploy-prod:
    name: Build and Deploy to PROD
    runs-on: ubuntu-latest
    environment: PROD
    needs: build-and-deploy-qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Pulls your repo code
      - name: Install Supabase CLI
        run: |
          wget -O /tmp/supabase.tar.gz https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
          cd /tmp
          tar -xzf supabase.tar.gz
          sudo cp supabase /usr/local/bin/
          sudo chmod +x /usr/local/bin/supabase
          supabase --version
        # Installs Supabase CLI globally
      - name: Run Supabase migrations (PROD)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.PROD_SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.PROD_SUPABASE_DB_PASSWORD }}
        run: |
          supabase link --project-ref ${{ secrets.PROD_SUPABASE_PROJECT_REF }}
          supabase db push --password $SUPABASE_DB_PASSWORD
        # Links to PROD Supabase project and applies migrations
      - name: Deploy Edge Functions (PROD)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.PROD_SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy --project-ref ${{ secrets.PROD_SUPABASE_PROJECT_REF }}
        # Deploys all edge functions to PROD environment

# Required secrets for QA and PROD:
# - QA_SUPABASE_ACCESS_TOKEN, QA_SUPABASE_PROJECT_REF, QA_SUPABASE_DB_PASSWORD
# - PROD_SUPABASE_ACCESS_TOKEN, PROD_SUPABASE_PROJECT_REF, PROD_SUPABASE_DB_PASSWORD
# - GITHUB_TOKEN (automatically provided)